feat: add test for presence of epic release in spack environment manifests

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -122,6 +122,10 @@ version:
       elif [[ "$CI_COMMIT_TAG" =~ ^v[0-9.]+\.[0-9]+\.[0-9]+ ]]; then
         VERSION="${CI_COMMIT_TAG:1}"
         EXPORT_TAG="${VERSION}"
+        for ENV_FILE in spack-environment/xl/spack.yaml spack-environment/cuda/spack.yaml; do
+          grep -- "- epic@${VERSION}" "${ENV_FILE}" >/dev/null \
+            || ( echo "Unable to locate epic release package for ${VERSION} in ${ENV_FILE}"; exit 1; )
+        done
       elif [[ "$CI_COMMIT_BRANCH" =~ ^v[0-9.]+\.[0-9]+-\(alpha\|beta\|stable\) ]]; then
         VERSION="${CI_COMMIT_BRANCH:1}"
         EXPORT_TAG="${VERSION}"
